### ISSUE TITLE
Regarding add_img_coords method in split_folds

### ISSUE THREAD

**Issue by vikalpjain91** [bamps53/kaggle-autonomous-driving2019#1]
Hi bamps53. I was referring to your code for autonomous car pose. Can you please elaborate a little about your code in:
https://github.com/bamps53/kaggle-autonomous-driving2019/blob/master/split_folds.py
@ line 30.
Why 3384 is used? Why that particular number?
What this r_heatmap and c_heatmap will do?
I am so glad if you can explain this to me.

**Comment by vikalpjain91** [comment]
is it the width of the image? or transformed width?

**Comment by vikalpjain91** [comment]
and r_heatmap and c_heatmap?

**Comment by bamps53** [comment]
3384 is image width.
r stand for row and c stands for column, so r_heatmap means row position in heat map.
We need to make heat map as a CenterNet target, and the heat map resolution is usually lower than input image.(in my model, heat map resolution is 4 times smaller than image.)
So I just calculated it beforehand.

**Comment by vikalpjain91** [comment]
Thank You so much for your response. Now it is clear.
